export const ASK_NEXT_REGION = 'ASK_NEXT_REGION'
export const REQUEST_DEVICE_ADDRESS_CONFIRM = 'REQUEST_DEVICE_ADDRESS_CONFIRM'
export const SAVE_THE_REGION_NAME = 'SAVE_THE_REGION_NAME'
export const SEARCH_BY_PERSISTENT_REGION = 'SEARCH_BY_PERSISTENT_REGION'
